### ISSUE TITLE
Error pip install pyopenjtalk

### ISSUE THREAD

**Issue by andersonfelipev** [pypa/pyproject-hooks#170]
oi estou tentando instalar o pyopenjtalk para poder excutar o codigo, mas está aparecedo esse erro

`(venv) PS D:\python\tts-teste\tacotron2-kaggle> pip install pyopenjtalk
Collecting pyopenjtalk
  Using cached pyopenjtalk-0.3.0.tar.gz (1.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      setup.py:26: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
        _CYTHON_INSTALLED = ver >= LooseVersion(min_cython_ver)
      Traceback (most recent call last):
        File "D:\python\tts-teste\tacotron2-kaggle\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "D:\python\tts-teste\tacotron2-kaggle\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "D:\python\tts-teste\tacotron2-kaggle\venv\lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel        
          return hook(config_settings)
        File "C:\Users\felip\AppData\Local\Temp\pip-build-env-q90m0xd4\overlay\Lib\site-packages\setuptools\build_meta.py", line 162, in get_requires_for_build_wheel
          return self._get_build_requires(
        File "C:\Users\felip\AppData\Local\Temp\pip-build-env-q90m0xd4\overlay\Lib\site-packages\setuptools\build_meta.py", line 143, in _get_build_requires
          self.run_setup()
        File "C:\Users\felip\AppData\Local\Temp\pip-build-env-q90m0xd4\overlay\Lib\site-packages\setuptools\build_meta.py", line 267, in run_setup
          super(_BuildMetaLegacyBackend,
        File "C:\Users\felip\AppData\Local\Temp\pip-build-env-q90m0xd4\overlay\Lib\site-packages\setuptools\build_meta.py", line 158, in run_setup
          exec(compile(code, __file__, 'exec'), locals())
        File "setup.py", line 153, in <module>
        File "C:\Users\felip\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 501, in run
          with Popen(*popenargs, **kwargs) as process:
        File "C:\Users\felip\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 969, in __init__
          self._execute_child(args, executable, preexec_fn, close_fds,
        File "C:\Users\felip\AppData\Local\Programs\Python\Python310\lib\subprocess.py", line 1438, in _execute_child
          hp, ht, pid, tid = _winapi.CreateProcess(executable, args,
      FileNotFoundError: [WinError 2] O sistema não pode encontrar o arquivo especificado
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
`

**Comment by takluyver** [comment]
That's an error coming from pyopenjtalk's `setup.py` file; `pyproject_hooks` is just part of the machinery that runs that.

It looks like it's trying to run some non-Python command which isn't found on your system.

See e.g. https://github.com/r9y9/pyopenjtalk/issues/32
